import argparse
import torch


def str2bool(value):
    if isinstance(value, bool):
        return value
    return str(value).lower() in {'1', 'true', 'yes', 'y'}


def add_base_arguments(parser):
    parser.add_argument('--data_path', default='./dataset/', type=str)
    parser.add_argument('--load_col_inter', nargs='+', default=['user_id', 'item_id', 'timestamp'])
    parser.add_argument('--model', default='SASRec')
    parser.add_argument('--dataset', default='Beauty')
    parser.add_argument('--gpu_id', default=0, type=int)
    parser.add_argument('--seed', default=2025, type=int)


def add_train_valid_args(parser):
    parser.add_argument('--train_batch_size', default=1024, type=int)
    parser.add_argument('--eval_batch_size', default=1024, type=int)
    parser.add_argument('--max_item_list_length', default=None, type=int)
    parser.add_argument('--learning_rate', default=1e-3, type=float)
    parser.add_argument('--epochs', default=300, type=int)
    parser.add_argument('--eval_split', default='LS', type=str)
    parser.add_argument('--eval_order', default='TO', type=str)
    parser.add_argument('--eval_group_by', default='user', type=str)
    parser.add_argument('--eval_valid_mode', default='full', type=str)
    parser.add_argument('--eval_test_mode', default='full', type=str)
    parser.add_argument('--eval_step', default=1, type=int)
    parser.add_argument('--stopping_step', default=10, type=int)
    parser.add_argument('--show_progress', default=True, type=str2bool)
    parser.add_argument('--verbose', default=True, type=str2bool)
    parser.add_argument('--topk', nargs='+', default=[5, 10, 20], type=int)
    parser.add_argument('--metrics', nargs='+', default=['Recall', 'NDCG'])
    parser.add_argument('--valid_metric', default='NDCG@10', type=str)
    parser.add_argument('--neg_sampling', default=None)
    parser.add_argument('--train_neg_sample_args', default=None)
    parser.add_argument('--checkpoint_dir', default='./ckpt/', type=str)
    parser.add_argument('--reproducibility', default=True, type=bool)


def add_cands_arguments(parser):
    parser.add_argument('--temperature', default=10.0, type=float)
    parser.add_argument('--norm_beta', default=1.0, type=float)
    parser.add_argument('--weight_gamma', default=0.10, type=float)
    parser.add_argument('--smooth_alpha', default=0.25, type=float)
    parser.add_argument('--pop_tau', default=1.0, type=float)
    parser.add_argument('--neighbor_k', default=16, type=int)
    parser.add_argument('--neighbor_window', default=3, type=int)
    parser.add_argument('--use_norm_residual', default=False, type=str2bool)
    parser.add_argument('--use_weighted_ce', default=False, type=str2bool)
    parser.add_argument('--use_cands_smoothing', default=False, type=str2bool)
    parser.add_argument('--bias_reg_weight', default=1e-4, type=float)
    parser.add_argument('--bias_init_scale', default=0.0, type=float)
    parser.add_argument('--temp_reg_weight', default=0.0, type=float)
    parser.add_argument('--data_temp_scale', default=3.0, type=float)
    parser.add_argument('--data_temp_min', default=1.0, type=float)
    parser.add_argument('--data_temp_max', default=100.0, type=float)
    parser.add_argument('--linear_lambda', default=0.0, type=float)
    parser.add_argument('--linear_topk', default=100, type=int)
    parser.add_argument('--linear_seq_decay', default=0.7, type=float)
    parser.add_argument('--linear_edge_decay', default=0.7, type=float)
    parser.add_argument('--linear_normalize', default=True, type=str2bool)
    parser.add_argument('--linear_use_bias', default=False, type=str2bool)
    parser.add_argument('--tail_cl_weight', default=0.0, type=float)
    parser.add_argument('--tail_cl_temperature', default=0.2, type=float)
    parser.add_argument('--tail_cl_quantile', default=0.33, type=float)
    parser.add_argument('--tail_cl_min_teacher_pop', default=20, type=int)
    parser.add_argument('--tail_cl_max_items', default=256, type=int)


def add_model_arguments(parser, base_model, dataset):
    if base_model in {'SASRec', 'CANDSSASRec', 'CalibratedCANDSSASRec', 'LearnableTempCANDSSASRec', 'DataAwareTempCANDSSASRec', 'LinearItemCANDSSASRec', 'TailCLCalibratedCANDSSASRec'}:
        parser.add_argument('--hidden_size', default=64, type=int)
        parser.add_argument('--n_layers', default=2, type=int)
        parser.add_argument('--n_heads', default=2, type=int)
        parser.add_argument('--inner_size', default=256, type=int)
        parser.add_argument('--hidden_dropout_prob', default=0.5, type=float)
        parser.add_argument('--attn_dropout_prob', default=0.5, type=float)
        parser.add_argument('--loss_type', default='CE', type=str)
        parser.add_argument('--hidden_act', default='gelu', type=str)
        parser.add_argument('--layer_norm_eps', default=1e-12, type=float)
        parser.add_argument('--initializer_range', default=0.02, type=float)
        if base_model in {'CANDSSASRec', 'CalibratedCANDSSASRec', 'LearnableTempCANDSSASRec', 'DataAwareTempCANDSSASRec', 'LinearItemCANDSSASRec', 'TailCLCalibratedCANDSSASRec'}:
            add_cands_arguments(parser)
    elif base_model == 'GRU4Rec':
        parser.add_argument('--hidden_size', default=64, type=int)
        parser.add_argument('--n_layers', default=1, type=int)
        parser.add_argument('--loss_type', default='CE', type=str)
        parser.add_argument('--hidden_dropout_prob', default=0.5, type=float)
    elif base_model == 'BERT4Rec':
        parser.add_argument('--hidden_size', default=64, type=int)
        parser.add_argument('--n_layers', default=2, type=int)
        parser.add_argument('--n_heads', default=2, type=int)
        parser.add_argument('--inner_size', default=256, type=int)
        parser.add_argument('--hidden_dropout_prob', default=0.5, type=float)
        parser.add_argument('--attn_dropout_prob', default=0.5, type=float)
        parser.add_argument('--loss_type', default='CE', type=str)
        parser.add_argument('--hidden_act', default='gelu', type=str)
        parser.add_argument('--layer_norm_eps', default=1e-12, type=float)
        parser.add_argument('--initializer_range', default=0.02, type=float)
        parser.add_argument('--bert_mask_ratio', default=0.2, type=float)
        parser.add_argument('--transform', default='mask_itemseq', type=str)
    elif base_model == 'CL4SRec':
        parser.add_argument('--aug_types', nargs='+', default=['crop', 'mask', 'reorder'])
        parser.add_argument('--crop_ratio', default=0.6, type=float)
        parser.add_argument('--mask_ratio', default=0.3, type=float)
        parser.add_argument('--reorder_ratio', default=0.6, type=float)
        parser.add_argument('--lmd', default=0.1, type=float)
        parser.add_argument('--tau', default=1.0, type=float)
        parser.add_argument('--sim', default='dot', type=str)
        parser.add_argument('--hidden_size', default=64, type=int)
        parser.add_argument('--n_layers', default=2, type=int)
        parser.add_argument('--n_heads', default=2, type=int)
        parser.add_argument('--inner_size', default=256, type=int)
        parser.add_argument('--hidden_dropout_prob', default=0.5, type=float)
        parser.add_argument('--attn_dropout_prob', default=0.5, type=float)
        parser.add_argument('--loss_type', default='CE', type=str)
        parser.add_argument('--hidden_act', default='gelu', type=str)
        parser.add_argument('--layer_norm_eps', default=1e-12, type=float)
        parser.add_argument('--initializer_range', default=0.02, type=float)
    elif base_model == 'DuoRec':
        parser.add_argument('--lmd', default=0.1, type=float)
        parser.add_argument('--lmd_sem', default=0.1, type=float)
        parser.add_argument('--tau', default=1.0, type=float)
        parser.add_argument('--sim', default='dot', type=str)
        parser.add_argument('--contrast', default='us_x', type=str)
        parser.add_argument('--same_target_path', default=f'./dataset/{dataset}/same_target.npy', type=str)
        parser.add_argument('--hidden_size', default=64, type=int)
        parser.add_argument('--n_layers', default=2, type=int)
        parser.add_argument('--n_heads', default=2, type=int)
        parser.add_argument('--inner_size', default=256, type=int)
        parser.add_argument('--hidden_dropout_prob', default=0.5, type=float)
        parser.add_argument('--attn_dropout_prob', default=0.5, type=float)
        parser.add_argument('--loss_type', default='CE', type=str)
        parser.add_argument('--hidden_act', default='gelu', type=str)
        parser.add_argument('--layer_norm_eps', default=1e-12, type=float)
        parser.add_argument('--initializer_range', default=0.02, type=float)
    elif base_model == 'ICLRec':
        parser.add_argument('--num_intent_cluster', default=512, type=int)
        parser.add_argument('--seq_representation_type', default='mean', type=str)
        parser.add_argument("--seq_representation_instancecl_type", default="concatenate", type=str)
        parser.add_argument('--intent_cf_weight', default=0.3, type=float)
        parser.add_argument('--aug_types', default=['crop', 'mask', 'reorder'], type=list)
        parser.add_argument('--crop_ratio', default=0.2, type=float)
        parser.add_argument('--mask_ratio', default=0.7, type=float)
        parser.add_argument('--reorder_ratio', default=0.2, type=float)
        parser.add_argument('--temperature', default=1.0, type=float)
        parser.add_argument('--sim', default='dot', type=str)
        parser.add_argument('--cf_weight', default=0.1, type=float)
        parser.add_argument('--de_noise', action='store_true')
        parser.add_argument('--warm_up_epoches', default=0, type=int)
        parser.add_argument('--hidden_size', default=64, type=int)
        parser.add_argument('--n_layers', default=2, type=int)
        parser.add_argument('--n_heads', default=2, type=int)
        parser.add_argument('--inner_size', default=256, type=int)
        parser.add_argument('--hidden_dropout_prob', default=0.5, type=float)
        parser.add_argument('--attn_dropout_prob', default=0.5, type=float)
        parser.add_argument('--loss_type', default='CE', type=str)
        parser.add_argument('--hidden_act', default='gelu', type=str)
        parser.add_argument('--layer_norm_eps', default=1e-12, type=float)
        parser.add_argument('--initializer_range', default=0.02, type=float)
    elif base_model == 'ICSRec':
        parser.add_argument('--cl_mode', default='cf', type=str)
        parser.add_argument('--num_intent_cluster', default=512, type=int)
        parser.add_argument('--lambda_0', default=0.2, type=float)
        parser.add_argument('--beta_0', default=0.1, type=float)
        parser.add_argument('--sim', default='dot', type=str)
        parser.add_argument('--temperature', default=1.0, type=float)
        parser.add_argument('--f_neg', action='store_true', default=True)
        parser.add_argument('--hidden_size', default=64, type=int)
        parser.add_argument('--n_layers', default=2, type=int)
        parser.add_argument('--n_heads', default=2, type=int)
        parser.add_argument('--inner_size', default=256, type=int)
        parser.add_argument('--hidden_dropout_prob', default=0.5, type=float)
        parser.add_argument('--attn_dropout_prob', default=0.5, type=float)
        parser.add_argument('--loss_type', default='CE', type=str)
        parser.add_argument('--hidden_act', default='gelu', type=str)
        parser.add_argument('--layer_norm_eps', default=1e-12, type=float)
        parser.add_argument('--initializer_range', default=0.02, type=float)
    elif base_model == 'IDURL':
        parser.add_argument('--hidden_size', default=64, type=int)
        parser.add_argument('--n_layers', default=2, type=int)
        parser.add_argument('--n_heads', default=2, type=int)
        parser.add_argument('--inner_size', default=256, type=int)
        parser.add_argument('--hidden_dropout_prob', default=0.5, type=float)
        parser.add_argument('--attn_dropout_prob', default=0.5, type=float)
        parser.add_argument('--loss_type', default='CE', type=str)
        parser.add_argument('--hidden_act', default='gelu', type=str)
        parser.add_argument('--layer_norm_eps', default=1e-12, type=float)
        parser.add_argument('--initializer_range', default=0.02, type=float)
        parser.add_argument('--n_facet_all', default=5, type=int)
        parser.add_argument('--new_repr_dp', default=1, type=int)
        parser.add_argument('--n_newc_repr', default=4, type=int)
        parser.add_argument('--disen_lambda', default=0.3, type=float)
        parser.add_argument('--idra', default=1, type=int)
        parser.add_argument('--align_lambda', default=0.4, type=float)
    elif base_model == 'IOCRec':
        parser.add_argument('--aug_types', default=['crop', 'mask', 'reorder'])
        parser.add_argument('--crop_ratio', default=0.2, type=float)
        parser.add_argument('--mask_ratio', default=0.7, type=float)
        parser.add_argument('--reorder_ratio', default=0.2, type=float)
        parser.add_argument('--lamda', default=0.1, type=float)
        parser.add_argument('--k_intention', default=4, type=int)
        parser.add_argument('--tao', default=1.0, type=float)
        parser.add_argument('--all_hidden', default=True, type=bool)
        parser.add_argument('--hidden_size', default=64, type=int)
        parser.add_argument('--n_layers', default=2, type=int)
        parser.add_argument('--n_heads', default=2, type=int)
        parser.add_argument('--inner_size', default=256, type=int)
        parser.add_argument('--hidden_dropout_prob', default=0.5, type=float)
        parser.add_argument('--attn_dropout_prob', default=0.5, type=float)
        parser.add_argument('--loss_type', default='CE', type=str)
        parser.add_argument('--hidden_act', default='gelu', type=str)
        parser.add_argument('--layer_norm_eps', default=1e-12, type=float)
        parser.add_argument('--initializer_range', default=0.02, type=float)
    elif base_model == 'WEARec':
        parser.add_argument('--num_heads', default=1, type=int)
        parser.add_argument('--alpha', default=0.8, type=float)
        parser.add_argument('--layer_norm_eps', default=1e-12, type=float)
        parser.add_argument('--hidden_dropout_prob', default=0.5, type=float)
        parser.add_argument('--hidden_size', default=64, type=int)
        parser.add_argument('--n_layers', default=2, type=int)
        parser.add_argument('--inner_size', default=256, type=int)
        parser.add_argument('--loss_type', default='CE', type=str)
        parser.add_argument('--hidden_act', default='gelu', type=str)
        parser.add_argument('--initializer_range', default=0.02, type=float)
    elif base_model == 'BSARec':
        parser.add_argument('--c', default=4, type=int)
        parser.add_argument('--alpha', default=0.5, type=float)
        parser.add_argument('--hidden_size', default=64, type=int)
        parser.add_argument('--n_layers', default=2, type=int)
        parser.add_argument('--n_heads', default=2, type=int)
        parser.add_argument('--inner_size', default=256, type=int)
        parser.add_argument('--hidden_dropout_prob', default=0.5, type=float)
        parser.add_argument('--attn_dropout_prob', default=0.5, type=float)
        parser.add_argument('--loss_type', default='CE', type=str)
        parser.add_argument('--hidden_act', default='gelu', type=str)
        parser.add_argument('--layer_norm_eps', default=1e-12, type=float)
        parser.add_argument('--initializer_range', default=0.02, type=float)
    elif base_model == 'ELCRec':
        parser.add_argument('--aug_types', nargs='+', default=['crop', 'mask', 'reorder'])
        parser.add_argument('--crop_ratio', default=0.2, type=float)
        parser.add_argument('--mask_ratio', default=0.7, type=float)
        parser.add_argument('--reorder_ratio', default=0.2, type=float)
        parser.add_argument('--num_intent_cluster', default=256, type=int)
        parser.add_argument('--seq_representation_type', default='mean', type=str)
        parser.add_argument('--seq_representation_instancecl_type', default='concatenate', type=str)
        parser.add_argument('--temperature', default=1.0, type=float)
        parser.add_argument('--cf_weight', default=0.1, type=float)
        parser.add_argument('--intent_cf_weight', default=0.1, type=float)
        parser.add_argument('--rec_weight', default=1.0, type=float)
        parser.add_argument('--trade_off', default=1.0, type=float)
        parser.add_argument('--de_noise', action='store_true')
        parser.add_argument('--warm_up_epoches', default=0, type=int)
        parser.add_argument('--hidden_size', default=64, type=int)
        parser.add_argument('--n_layers', default=2, type=int)
        parser.add_argument('--n_heads', default=2, type=int)
        parser.add_argument('--inner_size', default=256, type=int)
        parser.add_argument('--hidden_dropout_prob', default=0.5, type=float)
        parser.add_argument('--attn_dropout_prob', default=0.5, type=float)
        parser.add_argument('--loss_type', default='CE', type=str)
        parser.add_argument('--hidden_act', default='gelu', type=str)
        parser.add_argument('--layer_norm_eps', default=1e-12, type=float)
        parser.add_argument('--initializer_range', default=0.02, type=float)
    else:
        raise ValueError(f"Unsupported model: {base_model}")


def build_config_dict(args):
    config_dict = vars(args).copy()
    if config_dict.get('max_item_list_length') is None:
        config_dict['max_item_list_length'] = 200 if args.dataset == 'ML-1M' else 50
    config_dict['MAX_ITEM_LIST_LENGTH'] = config_dict.pop('max_item_list_length')
    config_dict['load_col'] = {'inter': config_dict.pop('load_col_inter'), 'item': ['item_id']}
    config_dict['eval_args'] = {
        'split': {config_dict.pop('eval_split'): 'valid_and_test'},
        'order': config_dict.pop('eval_order'),
        'group_by': config_dict.pop('eval_group_by'),
        'mode': {
            'valid': config_dict.pop('eval_valid_mode'),
            'test': config_dict.pop('eval_test_mode'),
        },
    }
    config_dict['use_gpu'] = torch.cuda.is_available()
        
    return config_dict


def parse_args():
    parser = argparse.ArgumentParser(add_help=False)
    add_base_arguments(parser)
    base_args, _ = parser.parse_known_args()
    add_train_valid_args(parser)
    parser.set_defaults(checkpoint_dir=f'./ckpt/{base_args.dataset}')
    add_model_arguments(parser, base_args.model, base_args.dataset)
    args, _ = parser.parse_known_args()
    return args
